// src/app/article/list/article-datas.js

const articleData = [
  {
    id: 1,
    title: 'Lorem Ipsum Dolor Sit Amet',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    image: 'https://via.placeholder.com/300x200',
    author: 'John Doe',
    date: '24 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '10:00 AM',
    readTime: '2 min',
    views: 1653,
    selected: true,
  },
  {
    id: 2,
    title: 'Sed Ut Perspiciatis Unde Omnis',
    description: 'Natus error sit voluptatem accusantium doloremque laudantium.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Jane Smith',
    date: '23 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '11:00 AM',
    readTime: '3 min',
    views: 1200,
    selected: false,
  },
  {
    id: 3,
    title: 'Eiusmod Tempor Incididunt Ut Labore',
    description: 'Excepteur sint occaecat cupidatat non proident.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Alice Johnson',
    date: '22 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '2:00 PM',
    readTime: '5 min',
    views: 980,
    selected: false,
  },
  {
    id: 4,
    title: 'Duis Aute Irure Dolor in reprehenderit',
    description: 'In voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Bob Brown',
    date: '21 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '3:00 PM',
    readTime: '4 min',
    views: 1550,
    selected: false,
  },
  {
    id: 5,
    title: 'Excepteur Sint Occaecat Cupidatat Non Proident',
    description: 'Sunt in culpa qui officia deserunt mollit anim id est laborum.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Charlie Davis',
    date: '20 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '4:00 PM',
    readTime: '6 min',
    views: 1100,
    selected: true,
  },
  {
    id: 6,
    title: 'Ut Enim Ad Minim Veniam',
    description: 'Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Eve Evans',
    date: '19 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '5:00 PM',
    readTime: '7 min',
    views: 1300,
    selected: false,
  },
  {
    id: 7,
    title: 'Curabitur Praesent Scelerisque',
    description: 'Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Frank Martin',
    date: '18 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '6:00 PM',
    readTime: '8 min',
    views: 900,
    selected: false,
  },
  {
    id: 8,
    title: 'Nunc Volutpat Venenatis Tellus',
    description: 'Pellentesque in ipsum id orci porta dapibus.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Hannah Lee',
    date: '17 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '7:00 PM',
    readTime: '5 min',
    views: 1350,
    selected: true,
  },
  {
    id: 9,
    title: 'Aenean Sit Amet Quam Vehicula',
    description: 'Sed porttitor lectus nibh. Curabitur arcu erat, accumsan id imperdiet et.',
    image: 'https://via.placeholder.com/300x200',
    author: 'George White',
    date: '16 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '8:00 PM',
    readTime: '4 min',
    views: 1100,
    selected: false,
  },
  {
    id: 10,
    title: 'Praesent Sapien Massa, Convallis',
    description: 'Nulla porttitor accumsan tincidunt.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Irene Taylor',
    date: '15 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '9:00 PM',
    readTime: '3 min',
    views: 1200,
    selected: false,
  },
  {
    id: 11,
    title: 'Nulla Quis Lorem Ut Libero',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Jack Wilson',
    date: '14 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '10:00 AM',
    readTime: '2 min',
    views: 1500,
    selected: false,
  },
  {
    id: 12,
    title: 'Aliquam Curabitur Non Nulla',
    description: 'Quis autem vel eum iure reprehenderit qui in ea voluptate.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Karen Brown',
    date: '13 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '11:00 AM',
    readTime: '6 min',
    views: 1600,
    selected: false,
  },
  {
    id: 13,
    title: 'Sed Do Eiusmod Tempor Incididunt',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Laura King',
    date: '12 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '12:00 PM',
    readTime: '7 min',
    views: 1300,
    selected: false,
  },
  {
    id: 14,
    title: 'Amet Consectetur Adipiscing Elit',
    description: 'Donec sollicitudin molestie malesuada.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Michael Scott',
    date: '11 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '1:00 PM',
    readTime: '3 min',
    views: 1400,
    selected: true,
  },
  {
    id: 15,
    title: 'Vivamus Suscipit Tortor Eget Felis',
    description: 'Proin eget tortor risus.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Nina Reed',
    date: '10 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '2:00 PM',
    readTime: '5 min',
    views: 1700,
    selected: false,
  },
  {
    id: 16,
    title: 'Curabitur Aliquet Quam Id Duo',
    description: 'Sed porttitor lectus nibh.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Oscar Miller',
    date: '09 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '3:00 PM',
    readTime: '2 min',
    views: 900,
    selected: false,
  },
  {
    id: 17,
    title: 'Pellentesque In Ipsum Id Orci',
    description: 'Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Paul Harris',
    date: '08 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '4:00 PM',
    readTime: '4 min',
    views: 800,
    selected: false,
  },
  {
    id: 18,
    title: 'Vivamus Suscipit Tortor Eget Felis',
    description: 'Pellentesque in ipsum id orci porta dapibus.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Quincy Allen',
    date: '07 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '5:00 PM',
    readTime: '7 min',
    views: 1000,
    selected: true,
  },
  {
    id: 19,
    title: 'Nulla Quis Lorem Ut Libero',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Rachel Green',
    date: '06 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '6:00 PM',
    readTime: '3 min',
    views: 1100,
    selected: false,
  },
  {
    id: 20,
    title: 'Sed Do Eiusmod Tempor Incididunt',
    description: 'Sed porttitor lectus nibh.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Steve Rogers',
    date: '05 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '7:00 PM',
    readTime: '6 min',
    views: 1500,
    selected: true,
  },
];

export default articleData;
