// src/app/article/list/article-datas.js

const articleData = [
  {
    id: 1,
    title: 'Lorem Ipsum Dolor Sit Amet',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    image: 'https://via.placeholder.com/300x200',
    author: 'John Doe',
    date: '24 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '10:00 AM',
    readTime: '2 min',
    views: 1653,
    selected: true, // This article is selected
  },
  {
    id: 2,
    title: 'Sed Ut Perspiciatis Unde Omnis',
    description: 'Natus error sit voluptatem accusantium doloremque laudantium.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Jane Smith',
    date: '23 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '11:00 AM',
    readTime: '3 min',
    views: 1200,
    selected: false,
  },
  {
    id: 3,
    title: 'Eiusmod Tempor Incididunt Ut Labore',
    description: 'Excepteur sint occaecat cupidatat non proident.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Alice Johnson',
    date: '22 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '2:00 PM',
    readTime: '5 min',
    views: 980,
    selected: false,
  },
  {
    id: 4,
    title: 'Duis Aute Irure Dolor in reprehenderit',
    description: 'In voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Bob Brown',
    date: '21 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '3:00 PM',
    readTime: '4 min',
    views: 1550,
    selected: false,
  },
  {
    id: 5,
    title: 'Excepteur Sint Occaecat Cupidatat Non Proident',
    description: 'Sunt in culpa qui officia deserunt mollit anim id est laborum.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Charlie Davis',
    date: '20 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '4:00 PM',
    readTime: '6 min',
    views: 1100,
    selected: true, // This article is selected
  },
  {
    id: 6,
    title: 'Ut Enim Ad Minim Veniam',
    description: 'Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    image: 'https://via.placeholder.com/300x200',
    author: 'Eve Evans',
    date: '19 August 2024',
    buttonlink: 'https://via.placeholder.com',
    time: '5:00 PM',
    readTime: '7 min',
    views: 1300,
    selected: false,
  },
];

export default articleData;
