import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "~/components/Navbar";
import Footer from "~/components/Footer";
import { mogula, rem } from "./fonts";
import ComingSoon from "~/components/ComingSoon";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout() {
  return (
    <html
      lang="en"
      className={`${rem.className} ${mogula.variable} ${rem.variable}`}
    >
      <body className="relative">
        <TRPCReactProvider>
          <ComingSoon />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
